// <auto-generated />
namespace Quan_ly_doan_vien.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tablechidoandoanvien : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tablechidoandoanvien));
        
        string IMigrationMetadata.Id
        {
            get { return "202103060934029_table-chidoan-doanvien"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
